#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-nifi
Version  : 1.6.0
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.jar
Source1  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.pom
Source2  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-client-dto/1.6.0/nifi-client-dto-1.6.0.jar
Source3  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-client-dto/1.6.0/nifi-client-dto-1.6.0.pom
Source4  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-commons/1.6.0/nifi-commons-1.6.0.pom
Source5  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-framework-api/1.6.0/nifi-framework-api-1.6.0.jar
Source6  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-framework-api/1.6.0/nifi-framework-api-1.6.0.pom
Source7  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-framework-bundle/1.6.0/nifi-framework-bundle-1.6.0.pom
Source8  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-framework/1.6.0/nifi-framework-1.6.0.pom
Source9  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-nar-bundles/1.6.0/nifi-nar-bundles-1.6.0.pom
Source10  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-properties/1.6.0/nifi-properties-1.6.0.jar
Source11  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-properties/1.6.0/nifi-properties-1.6.0.pom
Source12  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-security-utils/1.6.0/nifi-security-utils-1.6.0.jar
Source13  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-security-utils/1.6.0/nifi-security-utils-1.6.0.pom
Source14  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-site-to-site-client/1.6.0/nifi-site-to-site-client-1.6.0.jar
Source15  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-site-to-site-client/1.6.0/nifi-site-to-site-client-1.6.0.pom
Source16  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-utils/1.6.0/nifi-utils-1.6.0.jar
Source17  : https://repo1.maven.org/maven2/org/apache/nifi/nifi-utils/1.6.0/nifi-utils-1.6.0.pom
Source18  : https://repo1.maven.org/maven2/org/apache/nifi/nifi/1.6.0/nifi-1.6.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-nifi-data = %{version}-%{release}
Requires: mvn-nifi-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-nifi package.
Group: Data

%description data
data components for the mvn-nifi package.


%package license
Summary: license components for the mvn-nifi package.
Group: Default

%description license
license components for the mvn-nifi package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-nifi
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-nifi/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-nifi/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-api/1.6.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-api/1.6.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-client-dto/1.6.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-client-dto/1.6.0/nifi-client-dto-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-client-dto/1.6.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-client-dto/1.6.0/nifi-client-dto-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-commons/1.6.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-commons/1.6.0/nifi-commons-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-api/1.6.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-api/1.6.0/nifi-framework-api-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-api/1.6.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-api/1.6.0/nifi-framework-api-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-bundle/1.6.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-bundle/1.6.0/nifi-framework-bundle-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework/1.6.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework/1.6.0/nifi-framework-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-nar-bundles/1.6.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-nar-bundles/1.6.0/nifi-nar-bundles-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-properties/1.6.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-properties/1.6.0/nifi-properties-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-properties/1.6.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-properties/1.6.0/nifi-properties-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-security-utils/1.6.0
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-security-utils/1.6.0/nifi-security-utils-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-security-utils/1.6.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-security-utils/1.6.0/nifi-security-utils-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-site-to-site-client/1.6.0
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-site-to-site-client/1.6.0/nifi-site-to-site-client-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-site-to-site-client/1.6.0
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-site-to-site-client/1.6.0/nifi-site-to-site-client-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-utils/1.6.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-utils/1.6.0/nifi-utils-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-utils/1.6.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi-utils/1.6.0/nifi-utils-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi/1.6.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/nifi/nifi/1.6.0/nifi-1.6.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-api/1.6.0/nifi-api-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-client-dto/1.6.0/nifi-client-dto-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-client-dto/1.6.0/nifi-client-dto-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-commons/1.6.0/nifi-commons-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-api/1.6.0/nifi-framework-api-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-api/1.6.0/nifi-framework-api-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework-bundle/1.6.0/nifi-framework-bundle-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-framework/1.6.0/nifi-framework-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-nar-bundles/1.6.0/nifi-nar-bundles-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-properties/1.6.0/nifi-properties-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-properties/1.6.0/nifi-properties-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-security-utils/1.6.0/nifi-security-utils-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-security-utils/1.6.0/nifi-security-utils-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-site-to-site-client/1.6.0/nifi-site-to-site-client-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-site-to-site-client/1.6.0/nifi-site-to-site-client-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi-utils/1.6.0/nifi-utils-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/nifi/nifi-utils/1.6.0/nifi-utils-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/nifi/nifi/1.6.0/nifi-1.6.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-nifi/LICENSE
/usr/share/package-licenses/mvn-nifi/NOTICE
